repos:
-   repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: bash -c 'cd Source && dotnet tool run dotnet-format Dafny.sln -w --'
        types_or: ["c#"]
        
