repos:
-   repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format whitespace Source/Dafny.sln -v:d --include 
        types_or: ["c#"]
