repos:
-   repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet format whitespace Source/Dafny.sln -v:d --include
        exclude: 'GeneratedFromDafny|Source/DafnyRuntime/DafnyRuntimeSystemModule.cs'
        types_or: ["c#"]
