name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        If you are having trouble with a proof?  Consider posting your question on [Stack Overflow](https://stackoverflow.com/questions/ask?tags=dafny).	  
        Please do not report security issues on this public tracker.  Instead, see https://github.com/dafny-lang/dafny/blob/master/.github/SECURITY.md
  - type: dropdown
    id: dafnyversion
    attributes:
      label: What version of Dafny were you using?
      multiple: false
      options:
        - latest
        - 3.9.X
        - 3.8.X
        - 3.7.X
        - other
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Code to produce this issue.
      description: Please paste a minimal example that reproduces the issue.
      render: dafny
  - type: textarea
    id: environment
    attributes:
      label: Command to run into the issue or logs
      description: "Please paste here what you ran and what were your your logs that you think ought to be different:"
      render: code
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here. What did you expect instead?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
        - Other
    validations:
      required: true
      