name: Documentation error or request
description: Request change or addtion to Dafny documentation
title: "[doc]: "
labels: ["part: documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggested documentation improvement!
  - type: textarea
    id: what-do-you-want
    attributes:
      label: What change in documentation do you suggest?
      description: Describe the incorrect or desired documentation here`.
      placeholder: I suggest X
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
        - WSL
        - Other
