# Needed until we have replacable, to avoid duplicate module issues in the IDE
[options]
# Options that help support more values of consuming context options
# (mostly turning on any more restrictive verification)
track-print-effects = true
enforce-determinism = true
reads-clauses-on-methods = true

# Options important for sustainable development
# of the libraries themselves.
resource-limit = 1000
warn-as-errors = true
warn-redundant-assumptions = true
warn-contradictory-assumptions = true