doo_file_version = "1.0"
dafny_version = "4.3.0.0"
solver_identifier = "Z3"
solver_version = "4.12.1"
[options]
no-verify = false
unicode-char = true
enforce-determinism = true
relax-definite-assignment = false
reads-clauses-on-methods = true
track-print-effects = true
