name: Test that libraries verify

## Tests various aspects of documentation
##  -- Examples are well-formed and verify when expected
##  (Building the pdf is separately tested, in refman.yml)
##
## The tests only need to run on one OS -- Linux is used because the test scripts are bash

on:
  workflow_call:
    inputs:
      os:
        string

jobs:
  build-dafny:
    runs-on: ${{inputs.os}}

    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Checkout Dafny
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: dafny
    - name: Load Z3
      run: |
        sudo apt-get install -qq libarchive-tools
        mkdir -p dafny/Binaries/z3/bin
        wget -qO- https://github.com/dafny-lang/solver-builds/releases/download/snapshot-2023-02-17/z3-4.12.1-ubuntu-20.04-bin.zip | bsdtar -xf -
        mv z3-* dafny/Binaries/z3/bin/
        chmod +x dafny/Binaries/z3/bin/z3-*
    - name: Build Dafny
      run: dotnet build dafny/Source/Dafny.sln
    - name: Set up JS dependencies
      run: npm install bignumber.js
    - name: Install lit
      run: pip install lit OutputCheck
