name: Build Dafny

## A reusable workflow that builds dafny from the current master branch.
## It also loads Z3 and lit.
## (It does not currently load all compiler dependencies.)
## This is intended as a shared workflow for any client workflow that needs
## a current Dafny build in order to test something else.

## Use it like this:
##    uses: ./.github/workflows/build-reusable.yml
##    with:
##      os: ...
## where the argument to 'os' is the name of the OS for which to do the build, such as ubuntu-latest
## Currently always loads Z3 4.12.1 for ubuntu 20.04


on:
  workflow_call:
    inputs:
      os:
        string

jobs:
  build-dafny:
    runs-on: ${{inputs.os}}

    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Checkout Dafny
      uses: actions/checkout@v3
      with:
        submodules: recursive
        path: dafny
    - name: Load Z3
      run: |
        sudo apt-get install -qq libarchive-tools
        mkdir -p dafny/Binaries/z3/bin
        wget -qO- https://github.com/dafny-lang/solver-builds/releases/download/snapshot-2023-02-17/z3-4.12.1-ubuntu-20.04-bin.zip | bsdtar -xf -
        mv z3-* dafny/Binaries/z3/bin/
        chmod +x dafny/Binaries/z3/bin/z3-*
    - name: Build Dafny
      run: dotnet build dafny/Source/Dafny.sln
    - name: Set up JS dependencies
      run: npm install bignumber.js
    - name: Install lit
      run: pip install lit OutputCheck
