name: CompFuzzCI
on:
  pull_request:
    branches:
      - master
    types: [opened, closed, synchronize, reopened]
  issues:
    branches:
      - master
    types: [opened, closed, reopened]
  
jobs:
  FuzzOnPR:
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize') && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CompFuzzCI
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'CompFuzzCI',
                  repo: 'DafnyCompilerFuzzer',
                  workflow_id: 'fuzz.yaml',
                  ref: 'main',
                  inputs: {
                      commit: '${{ github.event.pull_request.head.sha }}',
                      main_commit: '${{github.event.pull_request.base.sha}}',
                      branch: '${{github.event.pull_request.head.ref}}',
                      duration: '3600',
                      instance: '5'
                  }
              })
  UpdatePRClosed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CompFuzzCI
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'CompFuzzCI',
                  repo: 'DafnyCompilerFuzzer',
                  workflow_id: 'update_pr_close.yaml',
                  ref: 'main',
                  inputs: {
                      pr_number: '${{github.event.number}}'
                  }
              })
  UpdateIssueOpened:
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')  && github.event.pull_request.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CompFuzzCI
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'CompFuzzCI',
                  repo: 'DafnyCompilerFuzzer',
                  workflow_id: 'update_issue_open.yaml',
                  ref: 'main',
                  inputs: {
                      issue_number: '${{github.event.issue.number}}',
                      issuer: '${{github.event.issue.user.login}}',
                      commit: ${{ github.sha }}                
                  }
              })
  UpdateIssueClosed:
    if: github.event_name == 'issues' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CompFuzzCI
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.COMPFUZZCI_PAT }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                  owner: 'CompFuzzCI',
                  repo: 'DafnyCompilerFuzzer',
                  workflow_id: 'update_issue_close.yaml',
                  ref: 'main',
                  inputs: {
                      issue_number: '${{github.event.issue.number}}'
                  }
              })