name: Test that libraries verify

## Tests various aspects of documentation
##  -- Examples are well-formed and verify when expected
##  (Building the pdf is separately tested, in refman.yml)
##
## The tests only need to run on one OS -- Linux is used because the test scripts are bash

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, main-* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-deep-tests:
     uses: ./.github/workflows/check-deep-tests-reusable.yml
     with:
       branch: master

  build:
    needs: check-deep-tests
    if: always() && (( github.event_name == 'pull_request' && (needs.check-deep-tests.result == 'success' || contains(github.event.pull_request.labels.*.name, 'run-deep-tests'))) || ( github.event_name == 'push' && ( github.ref_name == 'master' || vars.TEST_ON_FORK == 'true' )))
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build-reusable.yml

  library-tests:
    steps:
    - name: Checkout library
      uses: actions/checkout@v3
      with:
        repository: 'dafny-lang/libraries'
        path: libraries
    - name: Version information
      run: |
        ls dafny
        dafny/Scripts/dafny --version
    - name: Verify Code and Examples
      run: |
        cd libraries
        ../dafny/Scripts/dafny --version
        PATH=../dafny/Scripts:$PATH lit src
