name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        lit-test-paths: |
          allocated1 cloudmake comp dafny0 dafny1
          dafny2 dafny3 dafny4 DafnyTests exceptions
          exports git-issues hofs irondafny0 lambdas
          server triggers tutorial vacid0 VerifyThis2015
          VSComp2010 VSI-Benchmarks vstte2012 wishlist
    steps:
    - uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Checkout Boogie
      uses: actions/checkout@v2
      with:
        repository: boogie-org/boogie
        ref: v2.4.2
        path: boogie
    - name: Nuget Restore Boogie
      run: nuget restore boogie/Source/Boogie.sln
    - name: Build Boogie
      run: msbuild boogie/Source/Boogie.sln
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        path: dafny
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
        unzip z3*.zip && rm *.zip
        cp -r z3* dafny/Binaries/z3
    - name: Nuget Restore Dafny
      run: nuget restore dafny/Source/Dafny.sln
    - name: Build Dafny
      run: msbuild dafny/Source/Dafny.sln
    - uses: actions/setup-python@v1
    - name: Upgrade outdated pip
      run: python -m pip install --upgrade pip
    - name: Install lit
      run: pip install lit OutputCheck pyyaml
    - uses: actions/setup-node@v1
    - run: npm install bignumber.js
    - name: Run lit tests
      run: |
        cd dafny/Test
        lit --time-tests -v ${{ matrix.lit-test-paths }}
