name: Build and Test

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        ## Macos jobs tend to stall -- not including them for now
        os: [ubuntu-latest, ubuntu-16.04]
        ##os: [ubuntu-latest, windows-latest, ubuntu-16.04]
        ##os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-16.04]
        ## Size of the following array must match --num-shards in lit command
        ##shard: [1, 2, 3, 4, 5]
        shard: [1, 2, 3]
      fail-fast: false
    steps:
    - name: Manually sync certs
      if: runner.os == 'Linux'
      run: cert-sync /etc/ssl/certs/ca-certificates.crt
    - uses: actions/setup-python@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: C++ for ubuntu 16.04
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt-get install -y build-essential
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: dafny
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - uses: actions/setup-python@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Upgrade outdated pip
      run: python -m pip install --upgrade pip
    - name: Install lit
      run: pip install lit OutputCheck pyyaml
    - uses: actions/setup-node@v1
    - run: npm install bignumber.js
    - name: Create release
      run: python dafny/package.py 1.0.0 --os ubuntu
    - name: Unpack release
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq dafny/Package/dafny-1.0.0-x64-ubuntu-16.04.zip -d unzippedRelease
    - name: Run lit tests
      run: |
        sudo chmod +x $PWD/unzippedRelease/dafny/Dafny
        lit --time-tests -v --num-shards=5 --run-shard=${{ matrix.shard }} --param executable=$PWD/unzippedRelease/dafny/Dafny dafny/Test
