name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches: [ master, main-* ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


env:
  dotnet-version: 6.0.x # SDK Version for building Dafny

jobs:
  check-deep-tests:
    uses: ./.github/workflows/check-deep-tests-reusable.yml

  xunit-tests:
    needs: check-deep-tests
    if: always() && (( github.event_name == 'pull_request' && (needs.check-deep-tests.result == 'success' || contains(github.event.pull_request.labels.*.name, 'run-deep-tests'))) || ( github.event_name == 'push' && ( github.ref_name == 'master' || vars.TEST_ON_FORK == 'true' )))
    uses: ./.github/workflows/xunit-tests-reusable.yml

