name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Windows build is not yet working due to issues with the checked-in z3.exe
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
    - name: Manually sync certs
      run: cert-sync /etc/ssl/certs/ca-certificates.crt
    - name: Add msbuild to PATH
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Checkout Boogie
      uses: actions/checkout@v2
      with:
        repository: boogie-org/boogie
        ref: v2.4.21
        path: boogie
    - name: Nuget Restore Boogie
      run: nuget restore boogie/Source/Boogie.sln
    - name: Build Boogie
      run: msbuild boogie/Source/Boogie.sln
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        path: dafny
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
        unzip z3*.zip && rm *.zip
        cp -r z3* dafny/Binaries/z3
    - name: Nuget Restore Dafny
      run: nuget restore dafny/Dafny.sln
    - name: Build Dafny
      run: msbuild dafny/Dafny.sln
    - uses: actions/setup-node@v1
    - run: npm install bignumber.js
    - name: Run Dafny tests
      run: msbuild -t:Test dafny/Test/DafnyTests/DafnyTests.csproj
