
# This workflow includes more expensive tests than what is run on every PR, that are unlikely to break on most changes.
# It also publishes a nightly release.
name: Nightly test and release workflow

on:
  schedule:
    # Chosen to be hopefully outside of business hours for most contributors'
    # time zones, and not on the hour to avoid heavy scheduled-job times:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
#  deep-integration-tests:
#    uses: ./.github/workflows/integration-tests-reusable.yml
#    with:
#      all_platforms: true
#      num_shards: 5

  get-version:
    runs-on: ubuntu-22.04
    steps:
      - id: get-version
        uses: battila7/get-version-action@v2
    outputs:
      version: ${{ steps.get-version.outputs.version-without-v }}

  determine-vars:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Dafny
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.sha }}

      - name: Get short sha
        id: short-sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha_short }}
      date: ${{ steps.date.outputs.date }}
      name: nightly-${{ steps.date.outputs.date }}-${{ steps.short-sha.outputs.sha_short }}

  publish-release:
    uses: ./.github/workflows/publish-release-reusable.yml
    needs: [get-version, determine-vars]
#    needs: [deep-integration-tests, get-version, determine-vars]
    with:
      sha: refs/heads/master
      name: ${{ github.sha }}
      tag_name: nightly
      prerelease_name: ${{ needs.determine-vars.outputs.name }}
      release_nuget: false
      version: ${{ needs.get-version.outputs.version }}
      draft: false
      release_notes: "This is an automatically published nightly release. This release is not as stable as versioned releases and does not contain release notes."
