name: Publish Draft Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  dotnet-version: 6.0.x # SDK Version for building Dafny

jobs:
  check-deep-tests:
    uses: ./.github/workflows/check-deep-tests-reusable.yml
    with:
      sha: ${{ github.sha }}

  get-version:
    runs-on: ubuntu-22.04
    steps:
      - id: get-version
        uses: battila7/get-version-action@v2
      - run: echo ${{ steps.get-version.outputs.version }}
      - run: echo ${{ steps.get-version.outputs.version-without-v }}
    outputs:
      version: ${{ steps.get-version.outputs.version-without-v }}

  publish-release:
    needs: [get-version]
    uses: ./.github/workflows/publish-release-reusable.yml
    with:
      name: ${{ needs.get-version.outputs.version }}
      sha: ${{ github.sha }}
      tag_name: ${{ github.ref }}
      draft: true
      # Currently automated NuGet uploads have overly strict .NET
      # version dependencies. Skipping until that's fixed. See here:
      # https://github.com/dafny-lang/dafny/issues/2423
      release_nuget: false
      # We can probably automate pulling this out of RELEASE_NOTES.md in the future
      release_notes: ""
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
