name: Build DafnyRef.pdf

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout Dafny
        uses: actions/checkout@v2
      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - name: Install pandoc
        run: brew install pandoc
      - name: Install syntax highlighting
        run: gem install rouge
      - name: Install MacTex
        run: brew install mactex
      - name: Build DafnyRef.pdf
        run: make -C docs/DafnyReferenceManual 
      - name: Check
        run: ls -la docs/DafnyReferenceManual/DafnyRef.pdf
