name: Build DafnyRef.pdf

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Setup Nuget
      uses: nuget/setup-nuget@v1
    - name: Manually sync certs
      run: echo SKIPPING cert-sync /etc/ssl/certs/ca-certificates.crt
    - name: Add msbuild to PATH
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.0
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install mono
      run: brew install mono || echo OK
    - name: Checkout Boogie
      uses: actions/checkout@v2
      with:
        repository: boogie-org/boogie
        ref: v2.4.21
        path: boogie
    - name: Nuget Restore Boogie
      run: nuget restore boogie/Source/Boogie.sln
    - name: Build Boogie
      run: msbuild boogie/Source/Boogie.sln
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        path: dafny
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-osx-10.14.1.zip
        unzip z3*.zip && rm z3*.zip
        cp -r z3* dafny/Binaries/z3
    - name: Nuget Restore Dafny
      run: nuget restore dafny/Source/Dafny.sln
    - name: Build Dafny Parser
      run: make -C dafny/Source/Dafny -f Makefile.Linux
    - name: Build Dafny
      run: msbuild dafny/Source/Dafny.sln
    - name: Versions
      run: |
        dafny/Binaries/dafny -version
        dafny/Binaries/z3/bin/z3 -version
    - name: Install pandoc
      run: brew install pandoc
    - name: Install syntax highlighting
      run: echo SKIPPING gem install rouge
    - name: Install MacTex
      run: |
        brew cask install mactex
        eval "$(/usr/libexec/path_helper)"
    - name: CHeck install
      run: |
        which latex || echo NOT FOUND latex
        which xelatex || echo NOT FOUND xelatex
        find / -name latex || echo NOT FOUND latex
        find / -name xelatex || echo NOT FOUND xelatex
    - name: Build DafnyRef.pdf
      run: make -C dafny/docs/DafnyReferenceManual 
    - name: Check
      run: ls -la dafny/docs/DafnyReferenceManual/DafnyRef.pdf
