name: Test Brew release on Mac

on:
  workflow_dispatch:
  # This would make more sense as a scheduled build like deep-tests.yml
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install dafny
      run: |
        brew install dafny
    - name: Versions
      run: |
        which dafny
        dafny -version
        dotnet --list-sdks
        go version
        node --version
        java -version
        python --version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Perform smoke tests on each platform
      run: |
        wget https://github.com/dafny-lang/dafny/raw/master/Scripts/quicktest.sh
        wget https://github.com/dafny-lang/dafny/raw/master/Scripts/quicktest.out
        npm install bignumber.js
        chmod +x quicktest.sh
        ./quicktest.sh `which dafny` | tee tmp
        sed -i -e 'sx/usr/local/binx../../Scriptsx' tmp
        diff tmp quicktest.out
