name: Test Release Downloads

on:
  release:
    types: [ published ]
  # For manual testing through the Actions UI
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # This workflow breaks on windows-2022: https://github.com/dafny-lang/dafny/issues/1906
        os: [ ubuntu-latest, ubuntu-20.04, macos-latest, windows-2019 ]
        include:
        - os:  'ubuntu-22.04'
          osn: 'ubuntu\-22.04'
        - os:  'ubuntu-20.04'
          osn: 'ubuntu\-20.04'
        - os:  'macos-11'
          osn: 'x64-osx-.*'
        - os:  'windows-2019'
          osn: 'win'
    # There is no hosted environment for Ubuntu 14.04 or for debian

    # Java is installed by default, but we need to select 18

    steps:
    - name: OS
      run: echo ${{ runner.os }} ${{ matrix.os }}
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: 18
        distribution: corretto
    - name: Download ${{matrix.os}} releases
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: dafny-lang/dafny
        file: "dafny-.*-${{ matrix.osn }}\\.zip"
        regex: true
        target: "./"
    - name: Unzip, non-Windows
      if: runner.os != 'Windows'
      run: |
        unzip dafny*.zip && rm dafny*.zip
    - name: Unzip, Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        Expand-Archive dafny*.zip
        mv dafny*/dafny dafny
    - run: |
        pwd
        ls

  check:
    needs: build
    uses: ./.github/workflows/reusable-smoke-test.yml
    with:
      os: ${{ matrix.os }}
