name: Test Brew release on Mac

on:
  workflow_dispatch:
  # This would make more sense as a scheduled build like deep-tests.yml
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install dafny
      run: |
        brew install dafny || echo DONE
        brew link --overwrite dotnet
    - name: Make test program
      run: |
        echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
        echo "42" > expect.txt
    - name: Versions
      run: |
        dafny -version || echo OK
        which dafny
        # -version is not supported in old dafny,
        # but this gives the version with an error
        dotnet --list-sdks
        go version
        node --version
        java -version
    - name: Check
      run: dafny verify a.dfy
    - name: Check bad
      run: dafny verify b.dfy || echo EXPECTED FAILURE
    ## Check that a simple program compiles and runs on each supported platform
    - name: Check C# compile
      run: |
        dafny run -target:cs a.dfy > actual.txt
        diff expect.txt actual.txt
    - name: Check Go compile
      run: |
        dafny run --target:go a.dfy > actual.txt
        diff expect.txt actual.txt
    - name: Check Javascript compile
      run: |
        npm install bignumber.js
        dafny run --target:js a.dfy > actual.txt
        diff expect.txt actual.txt
    - name: Check Java compile
      run: |
        (ls dafny/DafnyRuntime.jar || echo NO DafnyRuntime.jar )
        dafny run --target:java a.dfy > actual.txt
        diff expect.txt actual.txt
    - name: Check Python compile
      run: |
        dafny run --target:py a.dfy > actual.txt
        diff expect.txt actual.txt
