name: Test Windows Release Download

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Windows release
      run: |
        wget -q https://github.com/dafny-lang/dafny/releases/download/v3.0.0-pre-release-1/dafny-3.0.0-pre-1-x64-win.zip
        unzip dafny*.zip && rm dafny*.zip
        ls -R
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget -q https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-win.zip
        unzip z3*.zip && rm *.zip
        cp -r z3-* z3
    - name: Make test program
      run: |
        echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
    - name: Versions
      run: |
        ./z3/bin/z3 -version
        dafny/Dafny.exe -version
    - name: Check
      run: dafny/Dafny.exe /compile:0 a.dfy 
    - name: Check bad
      run: dafny/Dafny.exe /compile:0 b.dfy
    - name: Check
      run: dafny/Dafny.exe /compile:0 a.dfy /z3exe:z3/bin/z3
    - name: Check bad
      run: dafny/Dafny.exe /compile:0 b.dfy /z3exe:z3/bin/z3

