name: Test Windows Release Download

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: OS
      run: echo ${{ matrix.os }}
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Windows release
      run: wget 'https://github.com/dafny-lang/dafny/releases/download/v3.0.0-pre-release-1/dafny-3.0.0-pre-1-x64-win.zip' -outfile 'dafny.zip'
    - name: Unpack release
      run: |
        ls -R .
        unzip dafny*.zip && rm dafny*.zip
    - name: Get Z3
      run: |
        curl https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-win.zip
        unzip z3*.zip && rm *.zip
        cp -r z3-* z3
    - name: Make test program
      run: |
        echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
    - name: Versions
      run: |
        ./z3/bin/z3 -version
        dafny/Dafny.exe -help | head -2
    - name: Check
      run: dafny/dafny /compile:0 a.dfy 
    - name: Check bad
      run: dafny/dafny /compile:0 b.dfy || echo EXPECTED FAILURE
    - name: Check
      run: dafny/dafny /compile:0 a.dfy /z3exe:z3/bin/z3
    - name: Check bad
      run: dafny/dafny /compile:0 b.dfy /z3exe:z3/bin/z3 || echo EXPECTED FAILURE
    ## Check that a simple program compiles and runs on each supported platform
    - name: Check C# compile
      run: |
        dafny/dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
    - name: Check Go compile
      run: |
        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:go a.dfy
        ##go run a-go/src/a.go a-go/src/*/*.go dafny/DafnyRuntime.go
    - name: Check Javascript compile
      run: |
        npm install bignumber.js
        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:js a.dfy
        node a.js dafny/DafnyRuntime.js | tail -1 | diff - expect.txt
    - name: Check Java compile
      run: |
        ls dafny/DafnyRuntime.java || echo NO DafnyRuntime.java
        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy || echo EXPECTED FAILURE UNTIL DafnyRuntime.java is restored

