name: Test Brew release on Mac

on:
  workflow_dispatch:
  # This would make more sense as a scheduled build like deep-tests.yml
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  download-and-test:
    runs-on: macos-latest
    steps:
    - name: Install dafny
      run: |
        brew install dafny
    - name: Versions
      run: |
        dafny -version
        which dafny
    - name: Check
      run: |
        npm install bignumber.js
        cp /usr/local/Cellar/dafny/3.12.0/libexec/quicktest.sh .
        chmod +x quicktest.sh
        ./quicktest.sh  `which dafny`
