name: Test Brew installation on Mac

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    - name: Install dafny, mono, z3
      run: brew install dafny || echo DONE
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget -q https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-14.04.zip
        unzip z3*.zip && rm *.zip
        cp -r z3-* z3
        ./z3/bin/z3 -version
    - name: Make test program
      run: |
        echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
    - name: Dafny version
      run: |
        ls -la /usr/local/bin/*afny*
        dafny -version
    - name: Check
      run: dafny /compile:0 a.dfy
    - name: Check bad
      run: dafny /compile:0 b.dfy
    - name: Check
      run: dafny /compile:0 a.dfy /z3exe:z3/bin/z3
    - name: Check bad
      run: dafny /compile:0 b.dfy /z3exe:z3/bin/z3
