name: Test Brew installation on Mac

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Install brew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - name: Install dafny
        run: brew install dafny
      - name: Make test program
        run: |
          echo "method m() { assert true; }" > a.dfy
          echo "method m() { assert false; }" > b.dfy
      - name: Check
        run: dafny /compile:0 a.dfy
      - name: Check bad
        run: dafny /compile:0 b.dfy
