name: Test Windows Release Download

on:
  push:
    branches: [ master cok-834 ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: OS
      run: |
        echo ${{ runner.os }}
        pwd
        ls -R .
        ## For some reason, pwd is D:\a\dafny\dafny
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Windows release
      run: Invoke-WebRequest -Outfile dafnyX.zip -Uri  'https://github.com/dafny-lang/dafny/releases/download/v3.0.0-pre-release-1/dafny-3.0.0-pre-1-x64-win.zip' 
      shell: pwsh
    - name: Unpack release
      run: |
        Expand-Archive dafny*.zip
        mv dafnyX/dafny dafny
    - name: Get Z3
      run: |
        Invoke-WebRequest -Outfile z3X.zip -Uri  https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-win.zip
        Expand-Archive z3X.zip
        mv z3*/z3-* z3
    - name: Make test program
      run: |
        echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
    - name: Versions
      run: |
        dafny/Dafny.exe -version
        dafny/dafny -version 
        ./z3/bin/z3.exe -version
    - name: Check
      run: cat a.dfy && dafny/dafny /compile:0 a.dfy 
    - name: Check bad
      run: |
        Format-Hex b.dfy
        cat b.dfy
        dafny/dafny /compile:0 b.dfy || echo "EXPECTED FAILURE" ; exit 0
    - name: Check
      run: dafny/dafny /compile:0 a.dfy /z3exe:z3/bin/z3.exe
    - name: Check bad
      run: dafny/dafny /compile:0 b.dfy /z3exe:z3/bin/z3.exe || echo "EXPECTED FAILURE" ; exit 0
    ## Check that a simple program compiles and runs on each supported platform
    - name: Check C# compile
      run: |
        dafny/dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
    - name: Check Go compile
      run: |
        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:go a.dfy
        ##go run a-go/src/a.go a-go/src/*/*.go dafny/DafnyRuntime.go
    - name: Check Javascript compile
      run: |
        npm install bignumber.js
        dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:js a.dfy
        node a.js dafny/DafnyRuntime.js | tail -1 > actual.txt
        diff actual.txt expect.txt
    - name: Check Java compile
      ##run: |
        ##ls dafny/DafnyRuntime.java || echo NO DafnyRuntime.java
        ##dafny/dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy || echo EXPECTED FAILURE UNTIL DafnyRuntime.java is restored

