name: Test Windows Release Download

on:
  push:
    branches: [ * ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Make release dir
      run: mkdir Z && cd Z && pwd
    - name: Download Windows release
      run: |
        wget https://github.com/dafny-lang/dafny/releases/download/v3.0.0-pre-release-1/dafny-3.0.0-pre-1-x64-win.zip
        unzip dafny*.zip && rm dafny*.zip
        ls -R
    - name: Get Z3
      if: matrix.os != 'windows-latest'
      run: |
        wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-win.zip
        unzip z3*.zip && rm *.zip
        ls 
        cp z3-4.8.4* z3
        ./z3 -version
    - name: Make test program
      run: |
        echo "method m() { assert true; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
    - name: Dafny version
      run: dafny -version
    - name: Check
      run: dafny /compile:0 a.dfy /z3exe:z3
    - name: Check bad
      run: dafny /compile:0 b.dfy /z3exe:z3
