name: Test Brew release on Mac

on:
  workflow_dispatch:
  # This would make more sense as a scheduled build like deep-tests.yml
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Install dafny
      run: |
        brew install dafny
    - name: Versions
      run: |
        dafny -version
        which dafny
        pwd
        ls
    - name: Check
      run: |
        npm install bignumber.js
        dafny/quicktest.sh > tmp
        diff tmp dafny/quicktest.out
