name: Test Brew release on Mac

on:
  workflow_dispatch:
  # This would make more sense as a scheduled build like deep-tests.yml
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install dafny
      run: |
        brew install dafny
    - name: Versions
      run: |
        which dafny
        dafny -version
        dotnet --list-sdks
        go version
        node --version
        java -version
        python --version
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    ## The smoke tests were upgraded to be a script that internally
    ## checks results after 4.0. Up through 4.0, the script relied on
    ## visual check of the results.
    - name: Perform smoke tests on each platform
      run: |
        npm install bignumber.js
        cp /usr/local/Cellar/dafny/*/libexec/quicktest.sh .
        chmod +x quicktest.sh
        ./quicktest.sh `which dafny`
