name: Smoke tests of release (reusable)

on:
  workflow_call:
    inputs:
      os:
        requires: true
        type: string
jobs:
  runs-on: ${{ inputs.os }}
  smoke-test:
    steps:
    - name: Versions
      run: |
        dafny -version
        which dafny
        # -version is not supported in old dafny,
        # but this gives the version with an error
        dotnet --list-sdks
        go version
        node --version
        java -version
    - name: Make test program
      run: |
        echo "method Main() { assert true; print 42, '\n'; }" > a.dfy
        echo "method m() { assert false; }" > b.dfy
        echo "42" > expect.txt
    - name: Check
      run: dafny verify a.dfy
    - name: Check bad
      run: dafny verify b.dfy || echo EXPECTED FAILURE
    ## Check that a simple program compiles and runs on each supported platform
    - name: Check C# compile
      run: |
        dafny /compileVerbose:0 /compile:3 /compileTarget:cs /spillTargetCode:3 a.dfy
    - name: Check Go compile
      run: |
        dafny build -t:go a.dfy
        env GO111MODULE=auto GOPATH=$PWD/a-go go run a-go/src/a.go > actual.txt
        diff expect.txt actual.txt
    - name: Check Javascript compile
      run: |
        npm install bignumber.js
        dafny build -t:js a.dfy
        node a.js dafny/DafnyRuntime.js > actual.txt
        diff expect.txt actual.txt
    - name: Check Java compile
      run: |
        (ls dafny/DafnyRuntime.jar || echo NO DafnyRuntime.jar )
        #dafny /compile:3 /spillTargetCode:3 /compileTarget:java a.dfy
        #java -cp a:dafny/DafnyRuntime.jar a > actual.txt
        #diff expect.txt actual.txt
