name: Run XUnit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
    env:
      testPath1: Source/DafnyLanguageServer.Test/bin/Debug/net5.0
      testPath2: Source/DafnyPipeline.Test/bin/Debug/net5.0
      solutionPath: Source/Dafny.sln
      z3BaseUri: https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5
      z3: z3-4.8.5-x64-ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ${{env.solutionPath}}
    - name: Build
      run: dotnet build --no-restore ${{env.solutionPath}}
    - name: Load Z3
      shell: pwsh
      run: |
        Invoke-WebRequest ${{env.z3BaseUri}}/${{env.z3}}.zip -OutFile z3.zip
        Expand-Archive z3.zip .
        Remove-Item z3.zip
        Copy-Item ${{env.z3}} ${{env.testPath1}}/z3 -Recurse
        Copy-Item ${{env.z3}} ${{env.testPath2}}/z3 -Recurse
    - name: Set Z3 Permissions
      run: | 
        chmod +x ${{env.testPath1}}/z3/bin/z3
        chmod +x ${{env.testPath2}}/z3/bin/z3
    - name: Run Tests
      run: dotnet test --no-restore --verbosity normal Source/Dafny.sln
